require('dotenv').config();

const env = {
	PORT: process.env.PORT || 3000,
	JWT_SECRET: process.env.JWT_SECRET || 'change-me',
	FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
	FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
	FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
	FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
	FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
	FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
	FIREBASE_TEST_USER_EMAIL: process.env.FIREBASE_TEST_USER_EMAIL,
	FIREBASE_TEST_USER_PASSWORD: process.env.FIREBASE_TEST_USER_PASSWORD,
};

module.exports = env;
